In [1]:
# Dependencies
import sys
import pylab as plb
import numpy as np
import mountaincar
import DummyAgent as DA
import NeuralAgent_v1 as NA1

### Let's RUN IT!

In [ ]:
d = DA.DummyAgent()
d.visualize_trial()
plb.show()

# With our own agent

In [2]:
n_neurons = 50 # Actually a n_neuros x n_neurons grid
tau = 0.5 #Exploration temperature parameter
eta = 0.1 #Learning rate
gamma = 0.95 #Reward factor
lambda_eligibility = 0.95 #elegibility decay
a = NA1.NeuralAgent(n_neurons,tau,eta,gamma,lambda_eligibility)

[-150.         -146.32653061 -142.65306122 -138.97959184 -135.30612245
 -131.63265306 -127.95918367 -124.28571429 -120.6122449  -116.93877551
 -113.26530612 -109.59183673 -105.91836735 -102.24489796  -98.57142857
  -94.89795918  -91.2244898   -87.55102041  -83.87755102  -80.20408163
  -76.53061224  -72.85714286  -69.18367347  -65.51020408  -61.83673469
  -58.16326531  -54.48979592  -50.81632653  -47.14285714  -43.46938776
  -39.79591837  -36.12244898  -32.44897959  -28.7755102   -25.10204082
  -21.42857143  -17.75510204  -14.08163265  -10.40816327   -6.73469388
   -3.06122449    0.6122449     4.28571429    7.95918367   11.63265306
   15.30612245   18.97959184   22.65306122   26.32653061   30.        ]
3.67346938776
[-15.         -14.3877551  -13.7755102  -13.16326531 -12.55102041
 -11.93877551 -11.32653061 -10.71428571 -10.10204082  -9.48979592
  -8.87755102  -8.26530612  -7.65306122  -7.04081633  -6.42857143
  -5.81632653  -5.20408163  -4.59183673  -3.97959184  -3.36734694
  -2.755102

In [3]:
N_trials = 50
N_runs=1
max_steps = 100000 #Save stop if not working well
latencies = a.run(N_trials,N_runs,max_steps)
print(latencies)

Starting trial at position (-60.850639640409256,-4.371487777962643)


C:\Users\dunay\Desktop\Github Desktop\my_unsupNN\Project2\NeuralAgent_v1.py:181: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if self.action_old != None:


[ 0.          0.38400731  0.        ]
1834
Starting trial at position (-119.64055155962728,4.450469798365173)
[ 0.00101315  0.38176644  0.37630095]
914
Starting trial at position (-61.45533802612255,-0.11951815822644019)
[ 0.42708336  0.42498798  0.32796795]
1380
Starting trial at position (-113.56280725700807,2.812732154920436)
[ 0.77547511  0.44343386  0.34165459]
1323
Starting trial at position (-112.73347635358354,3.111215270745655)
[ 1.11990491  0.50657216  0.34528266]
372
Starting trial at position (-92.44722077683569,1.0159930908891432)
[ 1.11516572  0.94343072  0.35970832]
1436
Starting trial at position (-105.23841726834615,3.2486194054624793)
[ 1.01086806  1.35565395  0.43421987]
795
Starting trial at position (-54.13001228845761,3.7753498011900035)
[ 1.39551844  1.41175253  0.43436404]
3260
Starting trial at position (-106.26487093198503,-0.1896750295007843)
[ 1.3486824   1.82151188  0.48333691]
3466
Starting trial at position (-107.56178532544536,4.613752026305029)
[ 1.3411

In [ ]:
a.visualize_trial()
plb.show()